### ISSUE TITLE
Collect information on where and how the organisations publish reports

### ISSUE THREAD

**Issue by kremio** [tatortrechts/data.tatortrechts.de#1]
Go through the websites listed at https://verband-brg.de/index.php/ueber-uns/mitglieder and produce a list of where the reports are displayed and what information is available.

**Comment by kremio** [comment]
I setup a markdown file to collect this data (docs/Topology.md), and started adding information.
I created issues for all the other monitoring websites I found that still need to be surveyed, so progress on these tasks can be tracked.

**Comment by jfilter** [comment]
Here https://github.com/tatortrechts/data.tatortrechts.de/blob/master/Organisations.md
