### ISSUE TITLE
Gather a list of other sources of incidents reports

### ISSUE THREAD

**Issue by kremio** [tatortrechts/data.tatortrechts.de#18]
Here is one suggested on the Open Knowledge Germany Slack channel: 
https://www.leuchtlinie.de/chronik

Another from the 'Mut gegen Rechte Gewalt":
https://www.mut-gegen-rechte-gewalt.de/service/chronik-vorfaelle

From Der Tagesspiegel (suggested on the OK Slack channel):
https://www.tagesspiegel.de/politik/interaktive-karte-todesopfer-rechter-gewalt-in-deutschland-seit-der-wiedervereinigung/23117414.html

Please comment this issue with more sources

**Comment by jfilter** [comment]
https://www.kop-berlin.de/chronik

**Comment by jfilter** [comment]
https://github.com/tatortrechts/data.tatortrechts.de/blob/master/Organisations.md
