### ISSUE TITLE
Create a nomenclature to unify reports.

### ISSUE THREAD

**Issue by kremio** [tatortrechts/data.tatortrechts.de#8]
Based on the information in the topology document, produce a specification detailing what data constitute a report.
This should include information about required and optional properties and sample values.

Note that I might have used the wrong terminologies when it come to administrative divisions of districts (Landkreis) and municipalities. It might be better to use the German terminology.

**Comment by kremio** [comment]
There is a first draft here: https://github.com/kremio/right-wing-violence-de/blob/master/docs/ReportFormat.md

Comments and feedback very much appreciated!

**Comment by jfilter** [comment]
So for http://www.mobile-opferberatung.de/monitoring/chronik2018/ I don't have URI for each incident. Should I still at the general URL? Or should we add a new property to make sure URIs are unique?

**Comment by kremio** [comment]
I think Jana had the same problem. She proposed to solve it by appending the title or some other unique string that relates to the report. In the case of mobile-opferberatung.de, you could use the date and the municipality, for instance http://www.mobile-opferberatung.de/monitoring/chronik2018/#04-10-2018-aschersleben

**Comment by jfilter** [comment]
Yeah, that's a good idea. I also support the idea of having a unique URI per incident.

1) Another issue I run into: Some columns values, i.e. sources, are JSON objects. Morph only supports SQLite. There is a [SQLite JSON extension](https://www.sqlite.org/json1.html) but I think we can't use it. So I am stringifying the JSON objects for the columns. I am fine with it for now. I still like Morph and would like to continue using it.

2) I think columns that are always null don't have to present at the morph scraper, right? I think we can set the values to null when combining all the Morph scrapers. What do you think?

**Comment by kremio** [comment]
These are very good points. I've created a specific ticket for this topic, let's continue the conversation there ? https://github.com/codeforberlin/right-wing-violence-de/issues/20

**Comment by jfilter** [comment]
Now here https://github.com/tatortrechts/data.tatortrechts.de/blob/master/Format.md
